### ISSUE TITLE
please confirm that plugin work fine on another project 

### ISSUE THREAD

**Issue by Ceschref** [Gebes/native_ios_dialog#1]
-- Unhandled Exception: MissingPluginException(No implementation found for method showDialog on channel native_ios_dialog). 

I got this problem when I first call "NativeIosDialog". please confirm that plugin work fine on another project!

**Comment by gebes** [comment]
The plugin works perfectly fine on iOS. I just built it and as you can see on the screenshot, it works fine:
<img width="564" alt="Bildschirmfoto 2022-05-06 um 07 56 21" src="https://user-images.githubusercontent.com/35232234/167075156-d5de3fd6-0048-4af0-8177-12cc8e8d165c.png">

Can you give me more details, so that I can help you to resolve the problem? On which platform are building the App? What is your build target?

(And yes, the plugin works on other projects.)

**Comment by Ceschref** [comment]
I thought you just declare key method in your iOS folder , but you don't ever mention this in document. When I call your Widget then appear error "Unhandled Exception: MissingPluginException"

**Comment by gebes** [comment]
Can you provide more information? How did you add the plugin to your project? If you are on macOS and build for iOS everything should be fine, if you add the project via the pubspec.
